# Generated by Django 5.1.5 on 2025-02-07 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatmessage'),
        ),
    ]
