# Generated by Django 5.1.5 on 2025-03-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='AgreementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersettings', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Категория соглашения',
                'verbose_name_plural': 'Категории соглашений',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'Красный'), ('blue', 'Синий'), ('green', 'Зеленый'), ('yellow', 'Желтый')], max_length=20, verbose_name='Цвет')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('user_id_tg', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersettings', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_photos/', verbose_name='Фото')),
                ('bold_text', models.CharField(max_length=255, verbose_name='Текст жирный')),
                ('long_text', models.TextField(verbose_name='Длинный текст')),
                ('bold_text_en', models.CharField(max_length=255, verbose_name='Текст жирный (En)')),
                ('long_text_en', models.TextField(verbose_name='Длинный текст (En)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='custom_admin.agreementcategory', verbose_name='Категория')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersettings', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Пользовательское соглашение карточка',
                'verbose_name_plural': 'Пользовательское соглашение карточки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(verbose_name='Товары')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('room_number', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Завершен')], default='new', max_length=20, verbose_name='Статус')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.usersettings', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('room_number', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('guest_count', models.PositiveIntegerField(default=1, verbose_name='Количество человек')),
                ('date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('items', models.JSONField(blank=True, default=dict, null=True, verbose_name='Товары')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая сумма')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersettings', verbose_name='Магазин')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.employee', verbose_name='Сотрудник')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('room', models.CharField(max_length=10, verbose_name='Номер комнаты')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.employee', verbose_name='Ответственный сотрудник')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usersettings', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
