# Generated by Django 5.1.5 on 2025-03-06 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название категории (En)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название подкатегории')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название подкатегории (En)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='category_photos/', verbose_name='Фото')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items2', to='main.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегории',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название магазина')),
                ('website_url', models.SlugField(unique=True, verbose_name='Уникальный URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('tg_bot_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен бота Telegram')),
                ('tg_group_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID группы Telegram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersettings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки магазина',
                'verbose_name_plural': 'Настройки магазинов',
            },
        ),
        migrations.AddField(
            model_name='subcategory',
            name='user_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.usersettings', verbose_name='Магазин'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название товара (En)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (En)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menu_photos/', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.category', verbose_name='Категория')),
                ('user_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='main.usersettings', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Меню товаров',
            },
        ),
        migrations.CreateModel(
            name='Headertext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок (En)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='menu_photos/', verbose_name='Фото')),
                ('user_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_texts', to='main.usersettings', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заголовочный текст',
                'verbose_name_plural': 'Заголовочные тексты',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='user_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.usersettings', verbose_name='Магазин'),
        ),
    ]
