# Generated by Django 5.1.5 on 2025-01-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menuitem_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertext',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/'),
        ),
    ]
