# Generated by Django 5.1.5 on 2025-02-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_alter_booking_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.JSONField(default=dict, verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Общая сумма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество человек'),
        ),
    ]
