# Generated by Django 5.1.5 on 2025-02-10 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_remove_employee_telegram_user_alter_booking_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='InfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='info_cards/', verbose_name='Фото')),
                ('bold_text', models.CharField(max_length=255, verbose_name='Текст жирный')),
                ('long_text', models.TextField(verbose_name='Длинный текст')),
                ('bold_text_en', models.CharField(max_length=255, verbose_name='Текст жирный (En)')),
                ('long_text_en', models.TextField(verbose_name='Длинный текст (En)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_cards', to='custom_admin.agreementcategory', verbose_name='Категория')),
            ],
        ),
    ]
